using System.Data.Entity;
using FullStopDotNet2014.Data.Migrations;
using FullStopDotNet2014.Data.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace FullStopDotNet2014.Data
{
    /// <summary>
    /// DbContext generated by template that supplies authentication models
    /// </summary>
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection")
        {
            
        }

        public ApplicationDbContext(string nameOrConnectionString):base(nameOrConnectionString)
        {
            
        }

        public DbSet<TextResource> TextResources { get; set; }
        public DbSet<BlogPost> BlogPosts { get; set; }

        static ApplicationDbContext()
        {
            Database.SetInitializer(new MigrateDatabaseToLatestVersion<ApplicationDbContext, Configuration>());
        }
    }
}